### ISSUE TITLE
Compiled CSS with $until tag is not '$breakpoint - 1'

### ISSUE THREAD

**Issue by JayBox325** [sass-mq/sass-mq#98] opened 2017-01-06 12:06 UTC
I am using your breakpoints on a project and an $until query is not taking 1 away from my breakpoint. See below:

```
@include mq($until: breakpoint('xl')) {
    ...
}

@include mq($from: breakpoint('xl')) {
    ...
}
```

Is being compiled into:

```
@media (max-width: 60em) {
    ...
}
@media (min-width: 60em) {
    ...
}
```

In this case, some styles from the `$until` breakpoint are being displayed during the 1px overlap at the `$from` breakpoint causing some issues.

Thanks,
Jay

**Comment by kaelig** [comment] 2017-01-06 17:50
Thanks for reporting this, can you specify what version of Sass you are using?

Also, are you using a CSS minifier?

**Comment by kaelig** [comment] 2017-02-06 22:08
Closing this as it hasn't gotten any answers in a month.

**Closed by kaelig** 2017-02-06 22:08 UTC

**Comment by kaelig** [comment] 2017-02-06 22:09
Also, this is not a bug. Passing a number honors the passed value. Passing a keywords removes a "pixel".

See https://github.com/sass-mq/sass-mq/blob/master/_mq.scss#L188
